[theme]
primaryColor = "#EC407A"
backgroundColor = "#F1F8E9"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#2D5016"
font = "sans serif"

[logger]
level = "info"

[client]
showErrorDetails = true
toolbarMode = "minimal"

